# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.contrib.gis.db import models


class Grocery(models.Model):
    gid = models.AutoField(primary_key=True)
    status = models.CharField(max_length=1, blank=True, null=True)
    score = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    match_type = models.CharField(max_length=2, blank=True, null=True)
    side = models.CharField(max_length=1, blank=True, null=True)
    x = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    y = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    match_addr = models.CharField(max_length=135, blank=True, null=True)
    arc_street = models.CharField(max_length=60, blank=True, null=True)
    arc_city = models.CharField(max_length=40, blank=True, null=True)
    arc_state = models.CharField(max_length=20, blank=True, null=True)
    arc_zip = models.CharField(max_length=12, blank=True, null=True)
    store_name = models.CharField(max_length=254, blank=True, null=True)
    street = models.CharField(max_length=254, blank=True, null=True)
    city = models.CharField(max_length=254, blank=True, null=True)
    state = models.CharField(max_length=254, blank=True, null=True)
    zip = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    geom = models.PointField(srid=0, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'grocery'

class PublicHousing(models.Model):
    ogc_fid = models.AutoField(primary_key=True)
    loc_name = models.CharField(max_length=14, blank=True, null=True)
    status = models.CharField(max_length=1, blank=True, null=True)
    score = models.DecimalField(max_digits=19, decimal_places=11, blank=True, null=True)
    match_type = models.CharField(max_length=2, blank=True, null=True)
    side = models.CharField(max_length=1, blank=True, null=True)
    x = models.DecimalField(max_digits=19, decimal_places=11, blank=True, null=True)
    y = models.DecimalField(max_digits=19, decimal_places=11, blank=True, null=True)
    match_addr = models.CharField(max_length=135, blank=True, null=True)
    arc_addres = models.CharField(max_length=50, blank=True, null=True)
    arc_city = models.CharField(max_length=50, blank=True, null=True)
    arc_state = models.CharField(max_length=50, blank=True, null=True)
    arc_zipcod = models.CharField(max_length=10, blank=True, null=True)
    no = models.DecimalField(max_digits=19, decimal_places=11, blank=True, null=True)
    mixed_popu = models.CharField(max_length=254, blank=True, null=True)
    street_no = models.DecimalField(max_digits=19, decimal_places=11, blank=True, null=True)
    street = models.CharField(max_length=254, blank=True, null=True)
    city = models.CharField(max_length=254, blank=True, null=True)
    zip = models.DecimalField(max_digits=19, decimal_places=11, blank=True, null=True)
    state = models.CharField(max_length=254, blank=True, null=True)
    population = models.CharField(max_length=254, blank=True, null=True)
    wkb_geometry = models.PointField(blank=True, null=True)
    class Meta:
        managed = False
        db_table = 'public_housing'

class Landmarks(models.Model):
    ogc_fid = models.AutoField(primary_key=True)
    st_louis_field = models.CharField(db_column='st__louis_', max_length=254, blank=True, null=True)  # Field renamed because it contained more than one '_' in a row. Field renamed because it ended with '_'.
    constructi = models.CharField(max_length=254, blank=True, null=True)
    lat_dd = models.DecimalField(max_digits=19, decimal_places=11, blank=True, null=True)
    long_dd = models.DecimalField(max_digits=19, decimal_places=11, blank=True, null=True)
    wkb_geometry = models.PointField(srid=900914, blank=True, null=True)
    class Meta:
        managed = False
        db_table = 'landmarks'

class Prices(models.Model):
    # perhaps change HANDLE name to lowercaese in DB
    index = models.BigIntegerField(blank=True, null=True)
    handle = models.CharField(primary_key=True ,max_length=16, unique=True , blank=True )  # Field name made lowercase. 
    bldg_price = models.FloatField(blank=True, null=True)
    vb = models.TextField(db_column='VB', blank=True, null=True)  # Field name made lowercase.
    new_construction_price = models.FloatField(blank=True, null=True)
    nc = models.TextField(db_column='NC', blank=True, null=True)  # Field name made lowercase.
    side_lot_price = models.FloatField(blank=True, null=True)
    sl = models.TextField(db_column='SL', blank=True, null=True)  # Field name made lowercase.
    vacant_lot_price = models.FloatField(blank=True, null=True)
    vl = models.TextField(db_column='VL', blank=True, null=True)  # Field name made lowercase.
    parcel = models.OneToOneField('FinalVacant',unique=True) 
    class Meta:
        managed = False
        db_table = 'prices'

class FinalVacant(models.Model):
    gid = models.AutoField(primary_key=True)
    handle = models.CharField(max_length=16, blank=True, null=True, unique=True)
    price = models.OneToOneField(Prices) 
    siteaddr = models.CharField(max_length=40, blank=True, null=True)
    ownercat = models.CharField(max_length=254, blank=True, null=True)
    vl_final = models.CharField(max_length=254, blank=True, null=True)
    vb_final = models.CharField(max_length=254, blank=True, null=True)
    vl_a = models.CharField(max_length=254, blank=True, null=True)
    vl_b = models.CharField(max_length=254, blank=True, null=True)
    vl_c = models.CharField(max_length=254, blank=True, null=True)
    vl_d = models.CharField(max_length=254, blank=True, null=True)
    vl_e = models.CharField(max_length=254, blank=True, null=True)
    vl_f = models.CharField(max_length=254, blank=True, null=True)
    vb_a = models.CharField(max_length=254, blank=True, null=True)
    vb_b = models.CharField(max_length=254, blank=True, null=True)
    vb_c = models.CharField(max_length=254, blank=True, null=True)
    vb_d = models.CharField(max_length=254, blank=True, null=True)
    vb_e = models.CharField(max_length=254, blank=True, null=True)
    vb_f = models.CharField(max_length=254, blank=True, null=True)
    bd_vb17 = models.BigIntegerField(blank=True, null=True)
    lu1010 = models.BigIntegerField(blank=True, null=True)
    prclhasbld = models.BigIntegerField(blank=True, null=True)
    for_vb18 = models.BigIntegerField(blank=True, null=True)
    for_vl18 = models.BigIntegerField(blank=True, null=True)
    lra_vl = models.BigIntegerField(blank=True, null=True)
    lra_vb = models.BigIntegerField(blank=True, null=True)
    lra_gl = models.BigIntegerField(blank=True, null=True)
    dp_s2016 = models.BigIntegerField(blank=True, null=True)
    bp_s2016 = models.BigIntegerField(blank=True, null=True)
    op_s2016 = models.BigIntegerField(blank=True, null=True)
    condstruc = models.BigIntegerField(blank=True, null=True)
    condbu = models.BigIntegerField(blank=True, null=True)
    taxbalyear = models.BigIntegerField(blank=True, null=True)
    yrstaxdeli = models.BigIntegerField(blank=True, null=True)
    taxbal = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    forpropcat = models.BigIntegerField(blank=True, null=True)
    forbu_10 = models.BigIntegerField(blank=True, null=True)
    forbu_2 = models.BigIntegerField(blank=True, null=True)
    forbu_5 = models.BigIntegerField(blank=True, null=True)
    formc_10 = models.BigIntegerField(blank=True, null=True)
    formc_2 = models.BigIntegerField(blank=True, null=True)
    formc_5 = models.BigIntegerField(blank=True, null=True)
    forvbrp_10 = models.BigIntegerField(blank=True, null=True)
    forvbrp_2 = models.BigIntegerField(blank=True, null=True)
    forvbrp_5 = models.BigIntegerField(blank=True, null=True)
    foryard_10 = models.BigIntegerField(blank=True, null=True)
    foryard_2 = models.BigIntegerField(blank=True, null=True)
    foryard_5 = models.BigIntegerField(blank=True, null=True)
    lra_enterd = models.DateField(blank=True, null=True)
    lra_aqyear = models.BigIntegerField(blank=True, null=True)
    lra_tenure = models.BigIntegerField(blank=True, null=True)
    lra_usage = models.CharField(max_length=254, blank=True, null=True)
    lra_aqtype = models.CharField(max_length=254, blank=True, null=True)
    lra_status = models.CharField(max_length=254, blank=True, null=True)
    td3 = models.BigIntegerField(blank=True, null=True)
    td5 = models.BigIntegerField(blank=True, null=True)
    yrsvacant = models.BigIntegerField(blank=True, null=True)
    bldgscom = models.BigIntegerField(blank=True, null=True)
    comcat = models.CharField(max_length=254, blank=True, null=True)
    comtype = models.BigIntegerField(blank=True, null=True)
    comgrdflr = models.BigIntegerField(blank=True, null=True)
    comstories = models.CharField(max_length=254, blank=True, null=True)
    comyrblt = models.BigIntegerField(blank=True, null=True)
    comconst = models.CharField(max_length=254, blank=True, null=True)
    comapts = models.BigIntegerField(blank=True, null=True)
    bldgsres = models.BigIntegerField(blank=True, null=True)
    resunits = models.BigIntegerField(blank=True, null=True)
    resocctype = models.CharField(max_length=254, blank=True, null=True)
    resbsmt = models.CharField(max_length=254, blank=True, null=True)
    resbmfin = models.CharField(max_length=254, blank=True, null=True)
    resextwall = models.CharField(max_length=254, blank=True, null=True)
    reslivarea = models.BigIntegerField(blank=True, null=True)
    resstories = models.CharField(max_length=254, blank=True, null=True)
    resfullbat = models.BigIntegerField(blank=True, null=True)
    reshlfbath = models.BigIntegerField(blank=True, null=True)
    resac = models.BigIntegerField(blank=True, null=True)
    resacwin = models.BigIntegerField(blank=True, null=True)
    resch = models.BigIntegerField(blank=True, null=True)
    resattic = models.BigIntegerField(blank=True, null=True)
    resgarage = models.BigIntegerField(blank=True, null=True)
    resyrblt = models.BigIntegerField(blank=True, null=True)
    cityblock = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    parcel = models.BigIntegerField(blank=True, null=True)
    ownercode = models.BigIntegerField(blank=True, null=True)
    parcelid = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    lowaddnum = models.BigIntegerField(blank=True, null=True)
    lowaddsuf = models.CharField(max_length=254, blank=True, null=True)
    highaddnum = models.BigIntegerField(blank=True, null=True)
    highaddsuf = models.CharField(max_length=254, blank=True, null=True)
    stpredir = models.CharField(max_length=254, blank=True, null=True)
    stname = models.CharField(max_length=254, blank=True, null=True)
    sttype = models.CharField(max_length=254, blank=True, null=True)
    stsufdir = models.CharField(max_length=254, blank=True, null=True)
    ownername = models.CharField(max_length=254, blank=True, null=True)
    ownername2 = models.CharField(max_length=254, blank=True, null=True)
    owneraddr = models.CharField(max_length=254, blank=True, null=True)
    ownercity = models.CharField(max_length=254, blank=True, null=True)
    ownerstate = models.CharField(max_length=254, blank=True, null=True)
    ownerzip = models.BigIntegerField(blank=True, null=True)
    asrclassco = models.BigIntegerField(blank=True, null=True)
    asrlanduse = models.BigIntegerField(blank=True, null=True)
    specbusdis = models.BigIntegerField(blank=True, null=True)
    specbusd_1 = models.BigIntegerField(blank=True, null=True)
    tifdist = models.BigIntegerField(blank=True, null=True)
    asdland = models.CharField(max_length=254, blank=True, null=True)
    asdimprove = models.CharField(max_length=254, blank=True, null=True)
    asdtotal = models.CharField(max_length=254, blank=True, null=True)
    aprland = models.CharField(max_length=254, blank=True, null=True)
    costaprimp = models.CharField(max_length=254, blank=True, null=True)
    cdalanduse = models.BigIntegerField(blank=True, null=True)
    zoning = models.CharField(max_length=254, blank=True, null=True)
    ressalepri = models.BigIntegerField(blank=True, null=True)
    ressaledat = models.DateField(blank=True, null=True)
    vacbldgyea = models.BigIntegerField(blank=True, null=True)
    geocityblo = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    ward10 = models.BigIntegerField(blank=True, null=True)
    precinct10 = models.BigIntegerField(blank=True, null=True)
    nbrhd = models.BigIntegerField(blank=True, null=True)
    cdadist = models.BigIntegerField(blank=True, null=True)
    cdasubdist = models.BigIntegerField(blank=True, null=True)
    policedist = models.BigIntegerField(blank=True, null=True)
    censtract1 = models.BigIntegerField(blank=True, null=True)
    censblock1 = models.BigIntegerField(blank=True, null=True)
    houseconsd = models.BigIntegerField(blank=True, null=True)
    zip = models.BigIntegerField(blank=True, null=True)
    onfloodblo = models.BigIntegerField(blank=True, null=True)
    giscityblo = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    gisparcel = models.BigIntegerField(blank=True, null=True)
    gisownerco = models.BigIntegerField(blank=True, null=True)
    parcel9 = models.BigIntegerField(blank=True, null=True)
    owner = models.CharField(max_length=254, blank=True, null=True)
    vl_g = models.BigIntegerField(blank=True, null=True)
    bd_vb18 = models.BigIntegerField(blank=True, null=True)
    vl_mck = models.BigIntegerField(blank=True, null=True)
    vb = models.CharField(max_length=254, blank=True, null=True)
    nc = models.CharField(max_length=254, blank=True, null=True)
    sl = models.CharField(max_length=254, blank=True, null=True)
    vl = models.CharField(max_length=254, blank=True, null=True)
    handledbl = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    frontage = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    asrnbrhd = models.BigIntegerField(blank=True, null=True)
    violations = models.BigIntegerField(blank=True, null=True)
    acres = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    sqft = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    nhd_name = models.CharField(max_length=50, blank=True, null=True)
    vaccattext = models.CharField(max_length=50, blank=True, null=True)
    geom = models.MultiPolygonField(srid=0, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'final_vacant'
